version: "3"
services:
  webapp:
    build: .
    image: blog-webapp
    ports:
      - "8080:8080"
    volumes:
      - ".:/code"
    command: |
      /bin/bash -c "
        npm install && npm run dev
      "
